// Canonical icon names are backed by the [Lucide icon library](https://lucide.dev/icons/).
//
// The semantic-name API (the `ValidIconName` type and the default export) is kept exactly as
// before so that consuming code does not need to change. Only the icon components behind the
// names changed from Carbon to Lucide.
import React from "react";
import type { LucideIcon } from "lucide-react";
import {
    Activity,
    ArrowDown,
    ArrowDownWideNarrow,
    ArrowLeft,
    ArrowRight,
    ArrowRightFromLine,
    ArrowRightToLine,
    ArrowUp,
    ArrowUpDown,
    ArrowUpNarrowWide,
    Ban,
    Bell,
    Binary,
    Blend,
    Blocks,
    Bold,
    BookA,
    BookMarked,
    Bot,
    Boxes,
    Braces,
    Calendar,
    CalendarClock,
    ChartColumn,
    ChartPie,
    Check,
    CheckCheck,
    ChevronDown,
    ChevronFirst,
    ChevronLast,
    ChevronLeft,
    ChevronRight,
    ChevronsUpDown,
    ChevronUp,
    Circle,
    CircleAlert,
    CircleCheck,
    CircleDot,
    CircleHelp,
    CirclePlus,
    CircleStop,
    CircleUserRound,
    CircleX,
    Clock,
    CloudDownload,
    Code,
    Columns3,
    Combine,
    Compass,
    Copy,
    CopyPlus,
    CornerDownRight,
    Database,
    DatabaseZap,
    Download,
    Ellipsis,
    EllipsisVertical,
    Eraser,
    Eye,
    EyeOff,
    File,
    FileChartColumn,
    FileCheck2,
    FileCode,
    FileCode2,
    FileDigit,
    FileDown,
    FileJson,
    FileOutput,
    FilePlus2,
    FileSpreadsheet,
    FileText,
    FileWarning,
    Filter,
    FilterX,
    Flag,
    Focus,
    Folder,
    FormInput,
    GitCommitHorizontal,
    GitCompare,
    Globe,
    GripVertical,
    Hash,
    Highlighter,
    History,
    House,
    Image,
    Info,
    Italic,
    Keyboard,
    Languages,
    LayoutDashboard,
    LayoutTemplate,
    Link,
    List,
    ListChecks,
    ListOrdered,
    ListTree,
    LoaderCircle,
    Lock,
    LockOpen,
    LogOut,
    Mail,
    MapPinned,
    Maximize2,
    MemoryStick,
    Merge,
    MessageSquarePlus,
    MessagesSquare,
    Mic,
    MicOff,
    Milestone,
    Minimize2,
    Network,
    OctagonAlert,
    Palette,
    PanelRight,
    Pencil,
    Pin,
    Play,
    Puzzle,
    Redo2,
    RefreshCw,
    RotateCcw,
    Rows3,
    Ruler,
    Save,
    ScrollText,
    Search,
    Send,
    Server,
    Settings,
    Share2,
    ShieldCheck,
    Shuffle,
    Sigma,
    SkipForward,
    SlidersHorizontal,
    Snowflake,
    Sparkles,
    Square,
    SquareArrowOutUpRight,
    SquareCheck,
    SquareCode,
    SquareFunction,
    SquareMinus,
    Star,
    Store,
    Strikethrough,
    Table,
    Table2,
    ThumbsDown,
    ThumbsUp,
    Timer,
    ToggleLeft,
    Trash2,
    TriangleAlert,
    Type,
    Undo2,
    Unlink,
    Upload,
    User,
    UserCog,
    UserSearch,
    Wand,
    WandSparkles,
    Waypoints,
    Webhook,
    Workflow,
    Wrench,
    X,
    Zap,
} from "lucide-react";

/**
 * Wraps a Lucide icon so it renders as a *filled* shape (the fill follows the current
 * color). Used for the "filled" toggler states (e.g. a selected star or pin) so they are
 * visually distinct from their outline counterparts, which stay stroke-only.
 */
const filled = (IconSymbol: LucideIcon): LucideIcon =>
    React.forwardRef<SVGSVGElement, React.ComponentProps<LucideIcon>>(function FilledLucideIcon(props, ref) {
        return <IconSymbol ref={ref} fill="currentColor" {...props} />;
    });

const canonicalIcons = {
    "application-activities": Activity,
    "application-dataintegration": Boxes,
    "application-explore": Compass,
    "application-homepage": House,
    "application-legacygui": History,
    "application-mapping": Waypoints,
    "application-colors": Palette,
    "application-queries": DatabaseZap,
    "application-useraccount": CircleUserRound,
    "application-vocabularies": BookMarked,
    "application-warning": TriangleAlert,
    "application-hotkeys": Keyboard,
    "application-notification": Bell,
    "application-sidepanel": PanelRight,

    "artefact-chatlog": MessagesSquare,
    "artefact-commit": GitCommitHorizontal,
    "artefact-task-addprojectfiles": FilePlus2,
    "artefact-task-getprojectfiles": FileDown,
    "artefact-task-deleteprojectfiles": Trash2,
    "artefact-task-downloadfile": CloudDownload,
    "artefact-task-pivot": Rows3,
    "artefact-task-unpivot": Columns3,
    "artefact-task-concatenatetofile": FileOutput,
    "artefact-task-sqlupdatequeryoperator": Database,
    "artefact-task-customsqlexecution": Database,
    "artefact-task-sparqlselectoperator": DatabaseZap,
    "artefact-task-sparqlupdateoperator": Database,
    "artefact-task-sparqlcopyoperator": Copy,
    "artefact-task-xmlparseroperator": FileCode,
    "artefact-task-validatexsdoperator": FileCheck2,
    "artefact-task-ucumnormalizationtask": Ruler,
    "artefact-task-cancelworkflow": CircleStop,
    "artefact-task-triplerequestoperator": Waypoints,
    "artefact-task-restoperator": Webhook,
    "artefact-task-eccencarestoperator": Webhook,
    "artefact-task-multitablemerge": Combine,
    "artefact-task-jsonparseroperator": Braces,
    "artefact-task-searchaddresses": MapPinned,
    "artefact-task-sparkfunction": Zap,
    "artefact-task-eccencadataplatformgraphstorefileuploadoperator": Upload,
    "artefact-task-xsltoperator": FileCode2,
    "artefact-task-distinctby": Filter,
    "artefact-task-template": LayoutTemplate,
    "artefact-task-merge": Merge,
    "artefact-task-scheduler": CalendarClock,
    "artefact-task-sendemail": Mail,
    "artefact-dataset-binaryfile": FileDigit,
    "artefact-dataset-csv": FileSpreadsheet,
    "artefact-dataset-eccencadataplatform": Database,
    "artefact-dataset-snowflakejdbc": Snowflake,
    "artefact-dataset-inmemory": MemoryStick,
    "artefact-dataset-excel": FileSpreadsheet,
    "artefact-dataset-file": File,
    "artefact-dataset": Database,
    "artefact-dataset-jdbc": Database,
    "artefact-dataset-json": FileJson,
    "artefact-dataset-multicsv": FileSpreadsheet,
    "artefact-dataset-neo4j": Waypoints,
    "artefact-dataset-sparkview": Database,
    "artefact-dataset-sparqlendpoint": Globe,
    "artefact-dataset-sqlendpoint": Database,
    "artefact-dataset-xml": FileCode,
    "artefact-deprecated": OctagonAlert,
    "artefact-embedded": Database,
    "artefact-errorlog": FileWarning,
    "artefact-file": FileText,
    "artefact-linking": Link,
    "artefact-project": Folder,
    "artefact-rawdata": Binary,
    "artefact-ruleblock": Puzzle,
    "artefact-remote": Server,
    "artefact-report": FileChartColumn,
    "artefact-task": ScrollText,
    "artefact-transform": Blend,
    "artefact-uncategorized": CircleHelp,
    "artefact-workflow": Workflow,

    "data-boolean": ToggleLeft,
    "data-color": Palette,
    "data-sourcepath": ArrowRightFromLine,
    "data-targetpath": ArrowRightToLine,
    "data-string": Type,
    "data-date": Calendar,
    "data-time": Clock,
    "data-datetime": CalendarClock,
    "data-number": Hash,
    "data-sourceschema": Table2,
    "data-targetschema": Table,

    "entity-human": User,
    "entity-robot": Bot,

    "item-add-artefact": CirclePlus,
    "item-clone": CopyPlus,
    "item-comment": MessageSquarePlus,
    "item-copy": Copy,
    "item-download": Download,
    "item-draggable": GripVertical,
    "item-edit": Pencil,
    "item-magic-edit": WandSparkles,
    "item-evaluation": ChartColumn,
    "item-execution": Play,
    "item-info": Info,
    "item-launch": SquareArrowOutUpRight,
    "item-legend": List,
    "item-moremenu": EllipsisVertical,
    "item-question": CircleHelp,
    "item-reload": RefreshCw,
    "item-remove": Trash2,
    "item-reset": RotateCcw,
    "item-save": Save,
    "item-settings": Settings,
    "item-shuffle": Shuffle,
    "item-skip-forward": SkipForward,
    "item-start": Play,
    "item-stop": Square,
    "item-upload": Upload,
    "item-vertmenu": Ellipsis,
    "item-viewdetails": Eye,
    "item-hidedetails": EyeOff,
    "item-image": Image,

    "list-sortasc": ArrowUpNarrowWide,
    "list-sortdesc": ArrowDownWideNarrow,
    "list-sort": ArrowUpDown,

    "module-accesscontrol": UserCog,
    "module-annotation": Highlighter,
    "module-dashboard": LayoutDashboard,
    "module-gdprsearch": UserSearch,
    "module-integrations": Blocks,
    "module-linkedrules": Link,
    "module-marketplace": Store,
    "module-reports": FileChartColumn,
    "module-search": Search,
    "module-thesauri": BookA,
    "module-timetracker": Timer,
    "module-visualization": ChartPie,

    "navigation-back": ArrowLeft,
    "navigation-close": X,
    "navigation-down": ArrowDown,
    "navigation-extern": SquareArrowOutUpRight,
    "navigation-first": ChevronFirst,
    "navigation-forth": ArrowRight,
    "navigation-jump": CornerDownRight,
    "navigation-last": ChevronLast,
    "navigation-left": ArrowLeft,
    "navigation-next": ChevronRight,
    "navigation-previous": ChevronLeft,
    "navigation-right": ArrowRight,
    "navigation-up": ArrowUp,

    "operation-aggregation": Sigma,
    "operation-ai-generate": Sparkles,
    "operation-autolayout": Network,
    "operation-clear": X,
    "operation-commit": GitCommitHorizontal,
    "operation-comparison": GitCompare,
    "operation-erase": Eraser,
    "operation-filter": Filter,
    "operation-filteredit": SlidersHorizontal,
    "operation-filterremove": FilterX,
    "operation-filterreset": FilterX,
    "operation-focus": Focus,
    "operation-format-codeblock": SquareCode,
    "operation-format-text-code": Code,
    "operation-format-text-bold": Bold,
    "operation-format-text-italic": Italic,
    "operation-format-text-strikethrough": Strikethrough,
    "operation-format-list-bullet": List,
    "operation-format-list-checked": ListChecks,
    "operation-format-list-numbered": ListOrdered,
    "operation-fix": Wrench,
    "operation-link": Link,
    "operation-logout": LogOut,
    "operation-magic": Wand,
    "operation-merge": Merge,
    "operation-tour": Milestone,
    "operation-redo": Redo2,
    "operation-search": Search,
    "operation-send": Send,
    "operation-sharelink": Share2,
    "operation-transform": SquareFunction,
    "operation-translate": Languages,
    "operation-undo": Undo2,
    "operation-unlink": Unlink,

    "state-checked": SquareCheck,
    "state-checkedsimple": Check,
    "state-confirmed": ThumbsUp,
    "state-confirmed-all": CheckCheck, // "confirm all": double check
    "state-danger": CircleAlert,
    "state-declined": ThumbsDown,
    "state-declined-all": Ban, // "decline all": prohibition sign
    "state-flagged": Flag,
    "state-info": Info,
    "state-locked": Lock,
    "state-partlychecked": SquareMinus,
    "state-progress": LoaderCircle,
    "state-progress-error": CircleX,
    "state-progress-warning": TriangleAlert,
    "state-protected": ShieldCheck,
    "state-success": CircleCheck,
    "state-unchecked": Square,
    "state-unlocked": LockOpen,
    "state-warning": TriangleAlert,

    "toggler-caret": ChevronsUpDown,
    "toggler-carettop": ChevronUp,
    "toggler-caretright": ChevronRight,
    "toggler-caretdown": ChevronDown,
    "toggler-caretleft": ChevronLeft,
    "toggler-maximize": Maximize2,
    "toggler-minimize": Minimize2,
    "toggler-micon": Mic,
    "toggler-micoff": MicOff,
    "toggler-moveleft": ChevronLeft,
    "toggler-moveright": ChevronRight,
    "toggler-list": List,
    "toggler-radio": Circle,
    "toggler-radio-checked": CircleDot,
    "toggler-rowexpand": ChevronDown,
    "toggler-rowcollapse": ChevronUp,
    "toggler-showless": ChevronUp,
    "toggler-showmore": ChevronDown,
    "toggler-star-empty": Star,
    "toggler-star-filled": filled(Star),
    "toggler-table": Table,
    "toggler-tree": ListTree,
    "toggler-pin-empty": Pin,
    "toggler-pin-filled": filled(Pin),

    "form-template": FormInput,

    undefined: Ban,
};

const canonicalIconNames: Record<ValidIconName, IconComponentType> = canonicalIcons;

/** Lucide icon component type. */
export type LucideIconType = LucideIcon;
/**
 * The icon component behind a canonical name. Usually a Lucide component (a forward-ref SVG
 * component accepting a numeric `size` plus `className`/SVG props), so `BaseIcon` can render it.
 * The union also accepts arbitrary icon components (e.g. passed to `TestIcon`'s `tryout` prop).
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type IconComponentType = LucideIconType | React.ComponentType<any>;
export type ValidIconName = keyof typeof canonicalIcons;

export default canonicalIconNames;
