import * as icons from "@carbon/react/icons";
import { CarbonIconType as IconType } from "@carbon/react/icons";

const canonicalIcons = {
    "application-activities": icons.Activity,
    "application-dataintegration": icons.DataUnstructured,
    "application-explore": icons.Explore,
    "application-homepage": icons.Workspace,
    "application-legacygui": icons.ResetAlt,
    "application-mapping": icons.ModelBuilder,
    "application-queries": icons.DataView,
    "application-useraccount": icons.UserAvatar,
    "application-vocabularies": icons.Catalog,
    "application-warning": icons.WarningAlt,
    "application-hotkeys": icons.Keyboard,
    "application-notification": icons.Notification,

    "artefact-chatlog": icons.Chat,
    "artefact-commit": icons.Commit,
    "artefact-task-deleteprojectfiles": icons.TrashCan,
    "artefact-task-downloadfile": icons.CloudDownload,
    "artefact-task-pivot": icons.Transpose,
    "artefact-task-unpivot": icons.Transpose,
    "artefact-task-concatenatetofile": icons.DocumentExport,
    "artefact-dataset-csv": icons.Csv,
    "artefact-dataset-eccencadataplatform": icons.DataVis_1,
    "artefact-dataset-excel": icons.Xls,
    "artefact-dataset-file": icons.DataVis_1,
    "artefact-dataset": icons.Data_2,
    "artefact-dataset-jdbc": icons.Sql,
    "artefact-dataset-json": icons.Json,
    "artefact-dataset-multicsv": icons.Csv,
    "artefact-dataset-neo4j": icons.DataVis_1,
    "artefact-dataset-sparkview": icons.Sql,
    "artefact-dataset-sparqlendpoint": icons.DataVis_1,
    "artefact-dataset-sqlendpoint": icons.Sql,
    "artefact-dataset-xml": icons.Xml,
    "artefact-deprecated": icons.WarningSquare,
    "artefact-embedded": icons.DataBase,
    "artefact-errorlog": icons.WarningOther, // FIXME: we may check for a better icon
    "artefact-file": icons.Document,
    "artefact-linking": icons.Connect,
    "artefact-project": icons.Folder,
    "artefact-rawdata": icons.ScriptReference,
    "artefact-remote": icons.VirtualMachine,
    "artefact-report": icons.Report,
    "artefact-task": icons.Script,
    "artefact-transform": icons.DataRefinery,
    "artefact-uncategorized": icons.Unknown,
    "artefact-workflow": icons.ModelBuilder,

    "data-boolean": icons.Boolean,
    "data-sourcepath": icons.Data_2,
    "data-targetpath": icons.Data_1,
    "data-string": icons.StringText,
    "data-date": icons.Calendar,
    "data-time": icons.Time,
    "data-datetime": icons.EventSchedule,
    "data-number": icons.StringInteger,

    "entity-human": icons.User,
    "entity-robot": icons.Bot,

    "item-add-artefact": icons.AddAlt,
    "item-clone": icons.Replicate,
    "item-comment": icons.AddComment,
    "item-copy": icons.Copy,
    "item-download": icons.Download,
    "item-draggable": icons.Draggable,
    "item-edit": icons.Edit,
    "item-magic-edit": icons.MagicWand,
    "item-evaluation": icons.Analytics,
    "item-execution": icons.Run,
    "item-info": icons.Information,
    "item-launch": icons.Launch,
    "item-moremenu": icons.OverflowMenuVertical,
    "item-question": icons.Help,
    "item-reload": icons.Renew,
    "item-remove": icons.TrashCan,
    "item-reset": icons.Reset,
    "item-save": icons.Save,
    "item-settings": icons.Settings,
    "item-shuffle": icons.Shuffle,
    "item-skip-forward": icons.SkipForwardFilled,
    "item-start": icons.PlayFilledAlt,
    "item-stop": icons.StopFilledAlt,
    "item-upload": icons.Upload,
    "item-vertmenu": icons.OverflowMenuHorizontal,
    "item-viewdetails": icons.View,
    "item-hidedetails": icons.ViewOff,
    "item-image": icons.Image,

    "list-sortasc": icons.ArrowDown,
    "list-sortdesc": icons.ArrowUp,
    "list-sort": icons.ArrowsVertical,

    "module-accesscontrol": icons.UserAdmin,
    "module-annotation": icons.WatsonHealthTextAnnotationToggle,
    "module-dashboard": icons.Dashboard,
    "module-gdprsearch": icons.UserProfile,
    "module-integrations": icons.AppConnectivity,
    "module-linkedrules": icons.Connect,
    "module-reports": icons.ReportData,
    "module-search": icons.Search,
    "module-thesauri": icons.Book,
    "module-timetracker": icons.Timer,
    "module-visualization": icons.DataVis_1,

    "navigation-back": icons.ArrowLeft,
    "navigation-close": icons.Close,
    "navigation-down": icons.ArrowDown,
    "navigation-extern": icons.Launch,
    "navigation-first": icons.PageFirst,
    "navigation-forth": icons.ArrowRight,
    "navigation-jump": icons.JumpLink,
    "navigation-last": icons.PageLast,
    "navigation-left": icons.ArrowLeft,
    "navigation-next": icons.ChevronRight,
    "navigation-previous": icons.ChevronLeft,
    "navigation-right": icons.ArrowRight,
    "navigation-up": icons.ArrowUp,

    "operation-aggregation": icons.DataCollection,
    "operation-autolayout": icons.ChartNetwork,
    "operation-clear": icons.Close,
    "operation-commit": icons.Commit,
    "operation-comparison": icons.Compare,
    "operation-erase": icons.Erase,
    "operation-filteredit": icons.FilterEdit,
    "operation-filterremove": icons.FilterRemove,
    "operation-filter": icons.Filter,
    "operation-focus": icons.CenterSquare,
    "operation-format-codeblock": icons.CodeBlock,
    "operation-format-text-code": icons.Code,
    "operation-format-text-bold": icons.TextBold,
    "operation-format-text-italic": icons.TextItalic,
    "operation-format-text-strikethrough": icons.TextStrikethrough,
    "operation-format-list-bullet": icons.ListBulleted,
    "operation-format-list-checked": icons.ListChecked,
    "operation-format-list-numbered": icons.ListNumbered,
    "operation-fix": icons.Tools,
    "operation-link": icons.Link,
    "operation-logout": icons.Logout,
    "operation-magic": icons.MagicWand,
    "operation-merge": icons.DirectionMerge,
    "operation-redo": icons.Redo,
    "operation-search": icons.Search,
    "operation-sharelink": icons.CopyLink,
    "operation-transform": icons.Calculation,
    "operation-translate": icons.Translate,
    "operation-undo": icons.Undo,
    "operation-unlink": icons.Unlink,

    "state-checked": icons.CheckboxChecked,
    "state-checkedsimple": icons.Checkmark,
    "state-confirmed": icons.ThumbsUp,
    "state-danger": icons.ErrorFilled,
    "state-declined": icons.ThumbsDown,
    "state-info": icons.InformationFilled,
    "state-locked": icons.Locked,
    "state-partlychecked": icons.CheckboxIndeterminate,
    "state-protected": icons.DocumentProtected,
    "state-success": icons.CheckmarkFilled,
    "state-unchecked": icons.Checkbox,
    "state-unlocked": icons.Unlocked,
    "state-warning": icons.WarningAltFilled,

    "toggler-caret": icons.CaretSort,
    "toggler-caretright": icons.CaretRight,
    "toggler-caretdown": icons.CaretDown,
    "toggler-maximize": icons.Maximize,
    "toggler-minimize": icons.Minimize,
    "toggler-moveleft": icons.ChevronLeft,
    "toggler-moveright": icons.ChevronRight,
    "toggler-list": icons.List,
    "toggler-rowexpand": icons.RowExpand,
    "toggler-rowcollapse": icons.RowCollapse,
    "toggler-showless": icons.ChevronUp,
    "toggler-showmore": icons.ChevronDown,
    "toggler-star-empty": icons.Star,
    "toggler-star-filled": icons.StarFilled,
    "toggler-table": icons.Table,
    "toggler-tree": icons.TreeViewAlt,

    "form-template": icons.Parameter,

    undefined: icons.Undefined,
};

const canonicalIconNames: Record<ValidIconName, CarbonIconType> = canonicalIcons;

export type CarbonIconType = IconType;
export type ValidIconName = keyof typeof canonicalIcons;
export default canonicalIconNames;
