/**
 * shadcn/ui vendor drift check.
 *
 * The primitives in `src/_shadcn/ui/` are vendored via the shadcn CLI and are NOT reformatted
 * by repo tooling (see `src/_shadcn/index.ts` for the full policy). This script pins their
 * content with per-file SHA-256 hashes in a checked-in manifest so that any accidental edit —
 * or an upstream `shadcn add --overwrite` that wipes an intentional deviation — is caught in CI.
 *
 * Usage:
 *   node scripts/shadcn-drift.mjs check    # (yarn shadcn:drift)        fail on any drift
 *   node scripts/shadcn-drift.mjs update   # (yarn shadcn:drift:update) regenerate the manifest
 *
 * Manifest shape (scripts/shadcn-drift-manifest.json):
 *   {
 *     "note": "...",
 *     "files":     { "<file>": "<sha256>" },      // accepted baseline hash for every ui/ file
 *     "allowlist": { "<file>": { "reason": "...", "hash": "<sha256>" } }  // intentional deviations
 *   }
 *
 * A file passes when its current hash equals its baseline `files` hash OR an accepted
 * `allowlist` hash. Anything else (changed / new / missing) is reported as drift.
 */
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const UI_DIR = join(ROOT, "src", "_shadcn", "ui");
const MANIFEST_PATH = join(ROOT, "scripts", "shadcn-drift-manifest.json");

/**
 * Intentional deviations from pristine shadcn CLI output. Each entry is a file in `ui/` whose
 * content is knowingly patched; the reason is surfaced in the manifest and in drift output.
 * On `update` the current hash of these files is recorded as the accepted allowlist hash.
 */
const INTENTIONAL_DEVIATIONS = {
    "button.tsx": "cursor-pointer added on interactive button variants",
    "dropdown-menu.tsx": "cursor classes added at interactive item/trigger spots",
    "command.tsx": "data-[selected=true] styling to fix the cmdk selection-highlight bug (~line 124)",
    "badge.tsx": "rounded-md shape instead of the pristine pill shape",
};

function hashFile(filePath) {
    return createHash("sha256").update(readFileSync(filePath)).digest("hex");
}

function currentHashes() {
    const entries = {};
    for (const name of readdirSync(UI_DIR).sort()) {
        const full = join(UI_DIR, name);
        if (!statSync(full).isFile()) continue;
        entries[name] = hashFile(full);
    }
    return entries;
}

function readManifest() {
    return JSON.parse(readFileSync(MANIFEST_PATH, "utf8"));
}

function update() {
    const files = currentHashes();
    const allowlist = {};
    for (const [name, reason] of Object.entries(INTENTIONAL_DEVIATIONS)) {
        if (!(name in files)) {
            console.warn(`warning: allowlisted file "${name}" is not present in src/_shadcn/ui/`);
            continue;
        }
        allowlist[name] = { reason, hash: files[name] };
    }
    const manifest = {
        note: "Auto-generated by scripts/shadcn-drift.mjs. Per-file SHA-256 of vendored shadcn/ui primitives. Run `yarn shadcn:drift:update` to regenerate. See src/_shadcn/index.ts for the vendor policy.",
        files,
        allowlist,
    };
    writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 4) + "\n");
    console.log(
        `shadcn:drift: manifest regenerated for ${Object.keys(files).length} file(s) ` +
            `(${Object.keys(allowlist).length} intentional deviation(s)).`,
    );
}

function check() {
    const manifest = readManifest();
    const baseline = manifest.files ?? {};
    const allowlist = manifest.allowlist ?? {};
    const current = currentHashes();

    const drift = [];

    for (const [name, hash] of Object.entries(current)) {
        const acceptedHashes = new Set();
        if (baseline[name]) acceptedHashes.add(baseline[name]);
        if (allowlist[name]?.hash) acceptedHashes.add(allowlist[name].hash);

        if (!(name in baseline) && !(name in allowlist)) {
            drift.push(`  + ${name} — new file not tracked in the manifest (run \`yarn shadcn:drift:update\`)`);
        } else if (!acceptedHashes.has(hash)) {
            const note = allowlist[name]
                ? ` — intentional deviation expected (${allowlist[name].reason}); re-apply it or run \`yarn shadcn:drift:update\``
                : " — content changed; if intentional, run `yarn shadcn:drift:update`";
            drift.push(`  ~ ${name}${note}`);
        }
    }

    for (const name of Object.keys(baseline)) {
        if (!(name in current)) {
            drift.push(`  - ${name} — tracked in the manifest but missing from src/_shadcn/ui/`);
        }
    }

    if (drift.length > 0) {
        console.error("shadcn:drift: vendored shadcn/ui primitives drifted from the manifest:\n");
        console.error(drift.join("\n"));
        console.error("\nThese files are vendored CLI output and must not be hand-edited (see src/_shadcn/index.ts).");
        process.exit(1);
    }

    console.log(
        `shadcn:drift: OK — ${Object.keys(current).length} vendored file(s) match the manifest ` +
            `(${Object.keys(allowlist).length} accepted deviation(s)).`,
    );
}

const mode = process.argv[2];
if (mode === "update") {
    update();
} else if (mode === "check" || mode === undefined) {
    check();
} else {
    console.error(`shadcn:drift: unknown mode "${mode}" (expected "check" or "update")`);
    process.exit(2);
}
