name: "Push: package & tagged release"

on:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string
      ref:
        required: true
        type: string
      sectionChangelog:
        type: string
      onlyNpmPush:
        type: boolean
        default: false
    secrets:
      chromaticToken:
        required: true
      npmjsToken:
        required: true

jobs:
  push-tagged-release:
    runs-on: "ubuntu-latest"
    steps:
      - name: Check input vars
        run: |
          echo ${{ inputs.ref }}
          echo ${{ inputs.sha }}
          echo ${{ inputs.sectionChangelog }}
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}
      - uses: actions/setup-node@main
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
      - name: Set name vars
        id: info-vars
        run: |
          echo "sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          echo "tag=${{ inputs.ref }}" >> $GITHUB_OUTPUT
          echo "version=$(echo ${{ inputs.ref }} | cut -c2-)" >> $GITHUB_OUTPUT
      - name: Get changelog entry
        # only use for final releases -- for other pre-releases the changelog is visible in the PR
        if: inputs.onlyNpmPush != true
        id: info-changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ inputs.sectionChangelog }}
      - name: Install dependencies
        run: yarn install
      - name: Create dist JS
        run: yarn build:all
      - name: Create jest results
        # only use for final releases because it is necessary only in addition to storybook
        if: ${{ inputs.onlyNpmPush != true && inputs.sectionChangelog != 'Unreleased' }}
        run: yarn test:generate-output
      - name: Publish to Chromatic
        # publish storybook only for final releases -- for other pre-releases the storybook has a link in PR
        if: ${{ inputs.onlyNpmPush != true && inputs.sectionChangelog != 'Unreleased' }}
        id: chromatic-upload
        uses: chromaui/action@v11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.chromaticToken }}
          exitZeroOnChanges: true
      - name: Publish npm package
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npmjsToken }}
      - name: Publish release
        # only use for final releases and RCs -- other pre-releases do not need an official announcement
        if: inputs.onlyNpmPush != true
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.info-vars.outputs.tag }}
          body: |
            * NPM package: https://www.npmjs.com/package/@eccenca/gui-elements/v/${{ steps.info-vars.outputs.version }}
            ${{ if [[ ! "${{ inputs.sectionChangelog }}" =~ ^(Unreleased)$ ]]; then echo "* Storybook: ${{ steps.chromatic-upload.outputs.storybookUrl }}"; fi }}
            ${{ if [[ ! "${{ inputs.sectionChangelog }}" =~ ^(Unreleased)$ ]]; then echo "${{ steps.info-changelog.outputs.changes }}"; else echo "* Changelog: https://github.com/eccenca/gui-elements/blob/${{ inputs.ref }}/CHANGELOG.md#unreleased"; fi }}
          prerelease: ${{ steps.info-changelog.outputs.status == 'unreleased' }}
          token: ${{ secrets.GITHUB_TOKEN }}
