name: "Release: Create release branch"

on:
  workflow_dispatch:
    branches:
      - "develop"
      - "feature/prepareReleaseForDM-CMEM-4151" # TODO: only for testing, remove it later
    inputs:
      releasetype:
        description: 'Type of release'
        required: true
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Update package.json with new release candidate version
      id: create-version
      run: |
        yarn version --no-git-tag-version --preid "rc" --pre${{ github.event.inputs.releasetype }}
        echo "::set-output name=version::$(node -p -e "require('./package.json').version.split('-').shift()")"
    - name: Create release branch
      id: create-branch
      run: |
        git checkout -b release/v${{ steps.create-version.outputs.version }}
        echo "::set-output name=label::release/v${{ steps.create-version.outputs.version }}"
    - name: Commit version number update
      id: make-commit
      run: |
        git commit package.json --message "Prepare release ${{ github.event.inputs.versionName }}"
        echo "::set-output name=commit::$(git rev-parse HEAD)"
    - name: Push release branch
      run: git push origin ${{ steps.create-branch.outputs.label }}
    - name: Create pull request into main
      uses: thomaseizinger/create-pull-request@1.0.0
      with:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       head: release/v${{ github.event.inputs.versionName }}
       base: master
       title: v${{ github.event.inputs.versionName }} into master
       reviewers: ${{ github.event.issue.user.login }}
       body: |
           Created by Github workflow to create release branches.
           Updated version name: ${{ steps.make-commit.outputs.commit }}.
