name: ":cop: Test: project conventions"

on:
  push:
    branches-ignore:
      - "develop"
      - "main"
      - "next"
      - "legacy"
  pull_request:

jobs:
  test-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Test branch name
        # https://github.com/marketplace/actions/enforce-branch-name
        uses: finleyfamily/action-enforce-branch-name@master
        with:
          regex: '([a-z])+\/([a-z]).([aA-zZ\.\-\d])+'
          allowed_prefixes: "feature,release,fix,bugfix,hotfix,change,temp,test,dependabot,maintain"
          exclude: "main,develop,next,legacy"
  test-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Test existence of important files
        # https://github.com/marketplace/actions/file-existence
        id: check_files
        uses: andstor/file-existence-action@main
        with:
          files: "package.json, LICENSE, README.md, CHANGELOG.md"
      - name: 'Test for "## [Unreleased]" section in changelog'
        if: steps.check_files.outputs.files_exists == 'true'
        run: grep "## \[Unreleased\]" CHANGELOG.md
