name: "🧪 Test: code"

on:
  pull_request:
    paths:
      - ".github/workflows/test-code.yml"
      - "src/**.js"
      - "src/**.ts"
      - "src/**.tsx"
      - "src/**.css"
      - ".storybook/**.css"
      - "index.ts"
      - package.json
      - yarn.lock

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Test using Node.js
        uses: actions/setup-node@main
        with:
          node-version: "lts/krypton"
      - run: yarn install
      - run: yarn compile
      - run: yarn tailwind:build
      - run: yarn test:ci
      - run: yarn shadcn:drift
