name: "CI_02: Code tests"

on:
  pull_request:
    paths:
      - "src/**.js"
      - "src/**.ts"
      - "src/**.tsx"
      - "index.ts"
      - "**.scss"
      - package.json
      - yarn.lock

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn compile
      - run: yarn compile-scss
      - run: yarn test:ci
